/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useCallback, useMemo } from 'react';

const LanguageContext = createContext(null);

const translations = {
  uz: {
    'nav.home': 'Bosh sahifa',
    'nav.catalog': 'Katalog',
    'nav.promotions': 'Aksiyalar',
    'nav.about': 'Biz haqimizda',
    'nav.contact': 'Aloqa',
    'nav.cart': 'Savatcha',
    'nav.login': 'Kirish',
    'nav.signup': 'Ro\'yxatdan o\'tish',
    'nav.logout': 'Chiqish',
    'nav.search': 'Mahsulotlarni qidirish...',
    'nav.fruits': 'Mevalar',
    'nav.vegetables': 'Sabzavotlar',
    'nav.dairy': 'Sut mahsulotlari',
    'nav.meat': 'Go\'sht va Parranda',
    'nav.bakery': 'Pishiriqlar',
    'nav.drinks': 'Ichimliklar',
    'currency': 'so\'m',
    'topbar.promo': 'AKSIYA',
    'topbar.delivery': '100 000 so\'mdan yuqori buyurtmalar uchun yetkazib berish bepul',
    'footer.description': 'Nihol - eng sara fermer mahsulotlari va kundalik ehtiyojlaringiz uchun ishonchli do\'kon. Har kuni yangi meva, sabzavot va go\'sht mahsulotlari.',
    'footer.pages': 'Sahifalar',
    'footer.contacts': 'Kontaktlar',
    'footer.rights': 'Barcha huquqlar himoyalangan.',
    'footer.about': 'Biz haqimizda',
    'footer.care': 'Mijozlar ko\'magi',
    'footer.contact': 'Biz bilan bog\'lanish',
    'footer.download': 'Yuklab oling',
    'footer.career': 'Karyera',
    'footer.stores': 'Do\'konlarimiz',
    'footer.mission': 'Bizning maqsadimiz',
    'footer.terms': 'Foydalanish shartlari',
    'footer.privacy': 'Maxfiylik siyosati',
    'footer.help': 'Yordam markazi',
    'footer.track': 'Buyurtmani kuzatish',
    'footer.b2b': 'Korporativ xaridlar',
    'footer.returns': 'Qaytarish va almashtirish',
    'footer.address': 'Toshkent shahar, Yunusobod tumani, Amir Temur shox ko\'chasi, 1A',
    'cart.empty': 'Savatchangiz bo\'sh',
    'cart.empty_desc': 'Hali hech qanday mahsulot qo\'shmadingiz. Keling, xaridni boshlaymiz!',
    'cart.start_shopping': 'Xaridni boshlash',
    'cart.summary': 'Buyurtma xulosasi',
    'cart.items_count': 'Mahsulotlar ({count} dona)',
    'cart.delivery': 'Yetkazib berish',
    'cart.free': 'Bepul',
    'cart.delivery_limit': '{limit} so\'mdan yuqori buyurtmalar uchun yetkazib berish bepul.',
    'cart.total': 'Jami',
    'cart.checkout': 'Rasmiylashtirish',
    'cart.continue': 'Xaridni davom ettirish',
    'cart.fast_delivery': 'Tez yetkazish',
    'cart.secure_payment': 'Xavfsiz to\'lov',
    'cart.select_all': 'Barchasini tanlash',
    'cart.selected': '{count} ta tanlandi',
    'login.title': 'Hisobga kirish',
    'login.desc': 'Xush kelibsiz! Davom etish uchun tizimga kiring.',
    'login.email_phone': 'Email yoki telefon',
    'login.password': 'Parol',
    'login.remember_me': 'Meni eslab qol',
    'login.forgot_password': 'Parolni unutdingizmi?',
    'login.submit': 'Kirish',
    'login.no_account': 'Hisobingiz yo\'qmi?',
    'signup.title': 'Ro\'yxatdan o\'tish',
    'signup.desc': 'Yangi hisob yarating va qulayliklardan foydalaning.',
    'signup.name': 'Ismingiz',
    'signup.email': 'Email pochta',
    'signup.phone': 'Telefon raqam',
    'signup.password': 'Parol yarating',
    'signup.submit': 'Ro\'yxatdan o\'tish',
    'signup.has_account': 'Hisobingiz bormi?',
    'product.add_to_cart': 'Savatchaga',
    'product.out_of_stock': 'Omborda qolmagan',
    'product.description': 'Tavsif',
    'product.reviews': 'Sharhlar ({count})',
    'product.rating': 'Reyting',
    'product.stock': 'Omborda: {count} dona',
    'product.weekly_buyers': 'Ushbu haftada {count} kishi sotib oldi',
    'breadcrumb.home': 'Bosh sahifa',
    'search.title': 'Qidiruv',
    'search.results': 'Qidiruv natijalari',
    'search.count': '{count} ta natija',
    'search.for': '"{query}" bo\'yicha',
    'search.clear': 'Qidiruvni tozalash',
    'search.notfound': 'Hech narsa topilmadi',
    'search.tryagain': 'Yuqoridagi qidiruvdan boshqa kalit so\'z bilan urinib ko\'ring.',
    'catalog.selectType': 'Mahsulot turini tanlang',
    'category.notfound': 'Kategoriya topilmadi',
    'category.notfoundDesc': 'Bunday kategoriya mavjud emas yoki o\'chirilgan.',
    'category.backToCatalog': 'Katalogga qaytish',
    'category.allCategories': 'Barcha kategoriyalar',
    'category.empty': 'Hozircha mahsulot yo\'q',
    'category.emptyDesc': 'Bu kategoriyaga tez orada yangi mahsulotlar qo\'shiladi.',
    'category.otherCategories': 'Boshqa kategoriyalar',
    'category.productsCount': '{count} ta mahsulot',
    'sort.recommended': 'Tavsiya etilgan',
    'sort.priceAsc': 'Avval arzoni',
    'sort.priceDesc': 'Avval qimmati',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.catalog': 'Каталог',
    'nav.promotions': 'Акции',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.cart': 'Корзина',
    'nav.login': 'Войти',
    'nav.signup': 'Регистрация',
    'nav.logout': 'Выйти',
    'nav.search': 'Поиск товаров...',
    'nav.fruits': 'Фрукты',
    'nav.vegetables': 'Овощи',
    'nav.dairy': 'Молочные продукты',
    'nav.meat': 'Мясо и птица',
    'nav.bakery': 'Выпечка',
    'nav.drinks': 'Напитки',
    'currency': 'сум',
    'topbar.promo': 'АКЦИЯ',
    'topbar.delivery': 'Бесплатная доставка при заказе от 100 000 сум',
    'footer.description': 'Nihol — ваш надежный магазин отборных фермерских продуктов и повседневных нужд. Свежие фрукты, овощи и мясо каждый день.',
    'footer.pages': 'Страницы',
    'footer.contacts': 'Контакты',
    'footer.rights': 'Все права защищены.',
    'footer.about': 'О нас',
    'footer.care': 'Поддержка клиентов',
    'footer.contact': 'Связаться с нами',
    'footer.download': 'Скачать',
    'footer.career': 'Карьера',
    'footer.stores': 'Наши магазины',
    'footer.mission': 'Наша миссия',
    'footer.terms': 'Условия использования',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.help': 'Центр поддержки',
    'footer.track': 'Отслеживание заказа',
    'footer.b2b': 'Корпоративные закупки',
    'footer.returns': 'Возврат и обмен',
    'footer.address': 'г. Ташкент, Юнусабадский район, проспект Амира Темура, 1А',
    'cart.empty': 'Ваша корзина пуста',
    'cart.empty_desc': 'Вы еще не добавили ни одного товара. Давайте начнем покупки!',
    'cart.start_shopping': 'Начать покупки',
    'cart.summary': 'Детали заказа',
    'cart.items_count': 'Товары ({count} шт.)',
    'cart.delivery': 'Доставка',
    'cart.free': 'Бесплатно',
    'cart.delivery_limit': 'Бесплатная доставка при заказе от {limit} сум.',
    'cart.total': 'Итого',
    'cart.checkout': 'Оформить заказ',
    'cart.continue': 'Продолжить покупки',
    'cart.fast_delivery': 'Быстрая доставка',
    'cart.secure_payment': 'Безопасная оплата',
    'cart.select_all': 'Выбрать все',
    'cart.selected': 'Выбрано: {count}',
    'login.title': 'Вход в аккаунт',
    'login.desc': 'Добро пожаловать! Войдите для продолжения.',
    'login.email_phone': 'Email или телефон',
    'login.password': 'Пароль',
    'login.remember_me': 'Запомнить меня',
    'login.forgot_password': 'Забыли пароль?',
    'login.submit': 'Войти',
    'login.no_account': 'Нет аккаунта?',
    'signup.title': 'Регистрация',
    'signup.desc': 'Создайте новый аккаунт и пользуйтесь удобствами.',
    'signup.name': 'Ваше имя',
    'signup.email': 'Email почта',
    'signup.phone': 'Номер телефона',
    'signup.password': 'Создайте пароль',
    'signup.submit': 'Зарегистрироваться',
    'signup.has_account': 'Уже есть аккаунт?',
    'product.add_to_cart': 'В корзину',
    'product.out_of_stock': 'Нет в наличии',
    'product.description': 'Описание',
    'product.reviews': 'Отзывы ({count})',
    'product.rating': 'Рейтинг',
    'product.stock': 'В наличии: {count} шт.',
    'product.weekly_buyers': 'Купили {count} человек на этой неделе',
    'breadcrumb.home': 'Главная',
    'search.title': 'Поиск',
    'search.results': 'Результаты поиска',
    'search.count': 'Найдено {count} результатов',
    'search.for': 'по запросу "{query}"',
    'search.clear': 'Сбросить поиск',
    'search.notfound': 'Ничего не найдено',
    'search.tryagain': 'Пожалуйста, попробуйте другие ключевые слова.',
    'catalog.selectType': 'Выберите категорию товаров',
    'category.notfound': 'Категория не найдена',
    'category.notfoundDesc': 'Такой категории не существует или она была удалена.',
    'category.backToCatalog': 'Назад в каталог',
    'category.allCategories': 'Все категории',
    'category.empty': 'Товаров пока нет',
    'category.emptyDesc': 'В эту категорию скоро будут добавлены новые товары.',
    'category.otherCategories': 'Другие категории',
    'category.productsCount': '{count} товаров',
    'sort.recommended': 'Рекомендуемые',
    'sort.priceAsc': 'Сначала дешевые',
    'sort.priceDesc': 'Сначала дорогие',
  },
  en: {
    'nav.home': 'Home',
    'nav.catalog': 'Catalog',
    'nav.promotions': 'Promotions',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.search': 'Search products...',
    'nav.fruits': 'Fruits',
    'nav.vegetables': 'Vegetables',
    'nav.dairy': 'Dairy Products',
    'nav.meat': 'Meat & Poultry',
    'nav.bakery': 'Bakery',
    'nav.drinks': 'Beverages',
    'currency': 'UZS',
    'topbar.promo': 'PROMO',
    'topbar.delivery': 'Free delivery for orders above 100,000 UZS',
    'footer.description': 'Nihol — your trusted store for selected farm fresh products and daily needs. Fresh fruits, vegetables, and meat every day.',
    'footer.pages': 'Pages',
    'footer.contacts': 'Contacts',
    'footer.rights': 'All rights reserved.',
    'footer.about': 'About Us',
    'footer.care': 'Customer Care',
    'footer.contact': 'Contact Us',
    'footer.download': 'Download',
    'footer.career': 'Careers',
    'footer.stores': 'Our Stores',
    'footer.mission': 'Our Mission',
    'footer.terms': 'Terms of Use',
    'footer.privacy': 'Privacy Policy',
    'footer.help': 'Help Center',
    'footer.track': 'Order Tracking',
    'footer.b2b': 'Corporate Sales',
    'footer.returns': 'Returns & Exchanges',
    'footer.address': '1A Amir Temur Ave, Yunusabad district, Tashkent',
    'cart.empty': 'Your cart is empty',
    'cart.empty_desc': 'You haven\'t added any products yet. Let\'s start shopping!',
    'cart.start_shopping': 'Start shopping',
    'cart.summary': 'Order Summary',
    'cart.items_count': 'Products ({count} items)',
    'cart.delivery': 'Delivery',
    'cart.free': 'Free',
    'cart.delivery_limit': 'Free delivery for orders above {limit} UZS.',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.continue': 'Continue Shopping',
    'cart.fast_delivery': 'Fast Delivery',
    'cart.secure_payment': 'Secure Payment',
    'cart.select_all': 'Select All',
    'cart.selected': '{count} selected',
    'login.title': 'Account Login',
    'login.desc': 'Welcome back! Sign in to continue.',
    'login.email_phone': 'Email or phone',
    'login.password': 'Password',
    'login.remember_me': 'Remember me',
    'login.forgot_password': 'Forgot password?',
    'login.submit': 'Login',
    'login.no_account': 'Don\'t have an account?',
    'signup.title': 'Register Account',
    'signup.desc': 'Create a new account and enjoy simple shopping.',
    'signup.name': 'Your Name',
    'signup.email': 'Email Address',
    'signup.phone': 'Phone Number',
    'signup.password': 'Create Password',
    'signup.submit': 'Register Now',
    'signup.has_account': 'Already have an account?',
    'product.add_to_cart': 'Add to Cart',
    'product.out_of_stock': 'Out of Stock',
    'product.description': 'Description',
    'product.reviews': 'Reviews ({count})',
    'product.rating': 'Rating',
    'product.stock': 'Stock: {count} pcs',
    'product.weekly_buyers': '{count} people bought this week',
    'breadcrumb.home': 'Home',
    'search.title': 'Search',
    'search.results': 'Search Results',
    'search.count': '{count} results found',
    'search.for': 'for "{query}"',
    'search.clear': 'Clear Search',
    'search.notfound': 'Nothing found',
    'search.tryagain': 'Please try searching with other keywords.',
    'catalog.selectType': 'Select category of products',
    'category.notfound': 'Category not found',
    'category.notfoundDesc': 'This category does not exist or has been removed.',
    'category.backToCatalog': 'Back to Catalog',
    'category.allCategories': 'All Categories',
    'category.empty': 'No products yet',
    'category.emptyDesc': 'New products will be added to this category soon.',
    'category.otherCategories': 'Other Categories',
    'category.productsCount': '{count} products',
    'sort.recommended': 'Recommended',
    'sort.priceAsc': 'Price: Low to High',
    'sort.priceDesc': 'Price: High to Low',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'uz');

  const setLanguage = useCallback((code) => {
    const validCodes = ['uz', 'ru', 'en'];
    const cleanCode = code.toLowerCase();
    if (validCodes.includes(cleanCode)) {
      setLang(cleanCode);
      localStorage.setItem('lang', cleanCode);
    }
  }, []);

  const t = useCallback((key, replaces = {}) => {
    let text = translations[lang]?.[key] || translations['uz']?.[key] || key;
    
    // Replace variables in key (e.g. {count})
    Object.entries(replaces).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });

    return text;
  }, [lang]);

  const value = useMemo(() => ({
    lang,
    setLanguage,
    t
  }), [lang, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useTranslation() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useTranslation must be used within LanguageProvider');
  return ctx;
}
